project:
  type: book

book:
  title: "Data Science in Focus"
  author: "Andrew Stewart"
  date: "4/12/2025"

  reader-mode: true

  favicon: cover.png
  image: cover.png
  cover-image: cover.png
  site-url: https://andrewcstewart.github.io/data-science-in-focus
  repo-url: https://github.com/andrewcstewart/data-science-in-focus
  repo-branch: main
  repo-actions: [edit, issue]
  
  sidebar:
    style: floating  # slim floating style like Modern Polars
    collapse-level: 2
    search: true    # background: "#F5F5F5"
    logo: cover.png

  navbar:
    background: "#2B5D63"
    foreground: "#F4F1E1"

  page-footer:
    left: "© 2025 Andrew Stewart"
    background: "#23494C"
    foreground: "#F4F1E1"

  chapters:
    - index.qmd

    - part: "**Defining Data Science**"
      chapters:
        - chapters/what-is-data-science.qmd
        - chapters/history-of-data-science.qmd
        - chapters/data-science-in-orgs.qmd
        - chapters/applied-systems-science.qmd

    - part: "**The Data Scientists**"
      chapters:
        - chapters/venn-data-science.qmd
        - chapters/t-model.qmd
        - chapters/team-sport.qmd

    - part: "**Research Management and Process**"
      chapters:
        - chapters/research-programs.qmd
        - chapters/scientific-method.qmd
        - chapters/capability-maturity.qmd

    - part: "**Tooling and Lab Practice**"
      chapters:
        - chapters/lab-workbench.qmd
        - chapters/documentation.qmd

    - part: "**Statistical Thinking**"
      chapters:
        - chapters/probability-inference.qmd

bibliography: chapters/references.bib

format:
  html:
    theme:
      light: custom-theme.scss
    css: styles.css
  # html:
  #   theme: cosmo  # or flatly
  #   toc: true
    number-sections: false
  #   code-copy: true
  #   # css: styles.css
  #   # include-in-header:
  #   #   - text: |
  #   #       <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">


  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true


